[[snapshot]]
datasets = ["fishtank"]
recursive = true
prune_keep = ['10', '1h:24', '1d:30', '4w']
pre_snapshot_script = "rsync -avx / /fishtank/rootfs"

[[snapshot]]
datasets = ["fishtank"]
prefix = "backup"
recursive = true
prune_keep = ['10', '1h:24', '1d:30', '4w']

[[snapshot]]
datasets = ["thinktank/srv", "thinktank/home"]
recursive = false  # The default.
take_snapshot = false
prune_keep = ['1w']
send_target = "septictank"
send_base = "thinktank"
